# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Feature Request
description: Issue to track a Feature Request / Modification
title: "Your Feature Request / Modification title"
type: 'Feature Request'
body:
  - type: markdown
    attributes:
      value: "## <ins>Feature Request Ticket creation</ins>"
  - type: textarea
    attributes:
      label: Feature Request / Modification Description
      description: |
        - Use following template within a PR and link it to this issue, if a new Feature is requested or the scope of an existing one is changed, otherwise just file a Task or Bug issue
          [Change Management Decision Record Template](https://eclipse-score.github.io/process_description/main/process_areas/change_management/guidance/change_management_decision_record_template.html)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Expected Changes of work products
      options:
        - label: Requirements
        - label: Architecture
        - label: Safety Analysis
        - label: Security Analysis
        - label: Detailed Design
        - label: Implementation and Testing
        - label: all  
    validations:
      required: true
  - type: textarea
    attributes:
      label: Impact analysis
      description: |
        - Summary of the impacted analysis, use the following template or parts and copy it to the decision record or in this issue field
        [Change Management Impact Analysis Template](https://eclipse-score.github.io/process_description/main/process_areas/change_management/guidance/change_management_impact_analysis_template.html)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Safety or Security relevance
      options:
        - label: none
        - label: Safety relevant
        - label: Security relevant
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Expected required ASIL classification
      options:
        - QM
        - ASIL_B
      default: 0
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Expected Implementation Version (Release)
      options:
        - '1.0'
        - '1.5'
        - '2.0'
        - '3.0'
      default: 0
    validations:
      required: false